<project name="scriptella-tools" default="jar">
    <path id="classpath">
        <pathelement location="${basedir}/../core/build/tmp/classes"/>
        <!-- Ant task sources compile against the running Ant (ant.home). -->
        <pathelement location="${ant.home}/lib/ant.jar"/>
    </path>
    <path id="test.classpath">
        <path refid="classpath"/>
        <pathelement location="${basedir}/../core/build/tmp/tests"/>
        <pathelement location="${basedir}/../lib/commons-logging.jar"/>
        <pathelement location="${basedir}/../lib/commons-jexl.jar"/>
        <pathelement location="${basedir}/../lib/h2.jar"/>
        <pathelement location="${basedir}/../lib/junit.jar"/>
    </path>
    <import file="../build-templates/build-template.xml"/>

</project>